services:
  - type: web
    name: rexi-backend
    runtime: docker
    rootDir: Backend
    plan: free
    healthCheckPath: /api/system/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: APP_FRONTEND_URL
        sync: false
      - key: COOKIE_SECURE
        value: "true"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: VNPAY_TMN_CODE
        sync: false
      - key: VNPAY_HASH_SECRET
        sync: false
      - key: VNPAY_RETURN_URL
        sync: false
