var Module = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  if (typeof __filename != 'undefined') _scriptName = _scriptName || __filename;
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var h=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;
h.preRun=function(){h.inputFiles.forEach(function(a){var b="/"+a.fileName,c=a.contents;a={};a.flags=a.flags||577;b=k(b,a.flags,a.mode);if("string"==typeof c){var d=new Uint8Array(ha(c)+1);c=ia(c,d,0,d.length);ja(b,d,0,c,void 0,a.ka)}else if(ArrayBuffer.isView(c))ja(b,c,0,c.byteLength,void 0,a.ka);else throw Error("Unsupported data type");ka(b)})};var la={...h},ma=[],na="./this.program",oa=(a,b)=>{throw b;},n="",pa,y;
if(fa){var fs=require("fs");require("path");n=__dirname+"/";y=a=>{a=qa(a)?new URL(a):a;return fs.readFileSync(a)};pa=async a=>{a=qa(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!h.thisProgram&&1<process.argv.length&&(na=process.argv[1].replace(/\\/g,"/"));ma=process.argv.slice(2);oa=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea)ea?n=self.location.href:"undefined"!=typeof document&&document.currentScript&&(n=document.currentScript.src),_scriptName&&(n=_scriptName),n.startsWith("blob:")?
n="":n=n.slice(0,n.replace(/[?#].*/,"").lastIndexOf("/")+1),ea&&(y=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),pa=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var ra=h.print||console.log.bind(console),z=h.printErr||console.error.bind(console);Object.assign(h,la);la=null;h.arguments&&(ma=h.arguments);h.thisProgram&&(na=h.thisProgram);
var sa=h.wasmBinary,A,ta=!1,C,D,ua,E,F,G,qa=a=>a.startsWith("file://");function va(){var a=A.buffer;h.HEAP8=C=new Int8Array(a);h.HEAP16=ua=new Int16Array(a);h.HEAPU8=D=new Uint8Array(a);h.HEAPU16=new Uint16Array(a);h.HEAP32=E=new Int32Array(a);h.HEAPU32=F=new Uint32Array(a);h.HEAPF32=new Float32Array(a);h.HEAPF64=new Float64Array(a);h.HEAP64=G=new BigInt64Array(a);h.HEAPU64=new BigUint64Array(a)}h.wasmMemory?A=h.wasmMemory:A=new WebAssembly.Memory({initial:(h.INITIAL_MEMORY||16777216)/65536,maximum:65536});
va();var H=0,I=null;function wa(){H++;h.monitorRunDependencies?.(H)}function xa(){H--;h.monitorRunDependencies?.(H);if(0==H&&I){var a=I;I=null;a()}}var ya;async function za(a){if(!sa)try{var b=await pa(a);return new Uint8Array(b)}catch{}if(a==ya&&sa)a=new Uint8Array(sa);else if(y)a=y(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Aa(a,b){try{var c=await za(a);return await WebAssembly.instantiate(c,b)}catch(d){throw z(`failed to asynchronously prepare wasm: ${d}`),a=d,h.onAbort?.(a),a="Aborted("+a+")",z(a),ta=!0,a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info."),ba(a),a;}}
async function Ba(a){var b=ya;if(!sa&&"function"==typeof WebAssembly.instantiateStreaming&&!fa)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){z(`wasm streaming compile failed: ${d}`),z("falling back to ArrayBuffer instantiation")}return Aa(b,a)}class Ca{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Da=a=>{for(;0<a.length;)a.shift()(h)},Ea=[],Fa=[],Ga=()=>{var a=h.preRun.shift();Fa.unshift(a)},Ha=h.noExitRuntime||!1,Ia=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},L=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ia(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ja=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ka=()=>{if(fa){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},La=a=>{(La=Ka())(a)},Ma=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ia(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Na="undefined"!=typeof TextDecoder?
new TextDecoder:void 0,Oa=(a,b=0)=>{b>>>=0;for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Na)return Na.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Pa=[],ha=a=>{for(var b=0,c=0;c<a.length;++c){var d=
a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ia=(a,b,c,d)=>{c>>>=0;if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var p=a.charCodeAt(++f);g=65536+((g&1023)<<10)|p&1023}if(127>=g){if(c>=d)break;b[c++>>>0]=g}else{if(2047>=g){if(c+1>=d)break;b[c++>>>0]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++>>>0]=224|g>>12}else{if(c+3>=d)break;b[c++>>>0]=240|g>>18;b[c++>>>0]=128|g>>12&63}b[c++>>>0]=128|g>>6&
63}b[c++>>>0]=128|g&63}}b[c>>>0]=0;return c-e},Qa=a=>{var b=Array(ha(a)+1);a=ia(a,b,0,b.length);b.length=a;return b},Ra=[];function Sa(a,b){Ra[a]={input:[],output:[],M:b};Ta(a,Ua)}
var Ua={open(a){var b=Ra[a.node.rdev];if(!b)throw new M(43);a.tty=b;a.seekable=!1},close(a){a.tty.M.fsync(a.tty)},fsync(a){a.tty.M.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.M.fa)throw new M(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.M.fa(a.tty)}catch(p){throw new M(29);}if(void 0===g&&0===e)throw new M(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.M.Y)throw new M(60);try{for(var e=0;e<d;e++)a.tty.M.Y(a.tty,b[c+e])}catch(f){throw new M(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Va={fa(){a:{if(!Pa.length){var a=null;if(fa){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}if(!a){a=null;break a}Pa=Qa(a)}a=Pa.shift()}return a},Y(a,b){null===b||10===b?(ra(Oa(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ra(Oa(a.output)),a.output=[])},ma(){return{wa:25856,ya:5,va:191,
xa:35387,ua:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},na(){return 0},oa(){return[24,80]}},Wa={Y(a,b){null===b||10===b?(z(Oa(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(z(Oa(a.output)),a.output=[])}},Ya=a=>{a=65536*Math.ceil(a/65536);var b=Xa(65536,a);b&&D.fill(0,b,b+a);return b},N={H:null,L(){return N.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(63);N.H||(N.H={dir:{node:{K:N.C.K,
I:N.C.I,lookup:N.C.lookup,S:N.C.S,rename:N.C.rename,unlink:N.C.unlink,rmdir:N.C.rmdir,readdir:N.C.readdir,symlink:N.C.symlink},stream:{G:N.A.G}},file:{node:{K:N.C.K,I:N.C.I},stream:{G:N.A.G,read:N.A.read,write:N.A.write,O:N.A.O,T:N.A.T}},link:{node:{K:N.C.K,I:N.C.I,readlink:N.C.readlink},stream:{}},da:{node:{K:N.C.K,I:N.C.I},stream:Za}});c=$a(a,b,c,d);O(c.mode)?(c.C=N.H.dir.node,c.A=N.H.dir.stream,c.B={}):32768===(c.mode&61440)?(c.C=N.H.file.node,c.A=N.H.file.stream,c.D=0,c.B=null):40960===(c.mode&
61440)?(c.C=N.H.link.node,c.A=N.H.link.stream):8192===(c.mode&61440)&&(c.C=N.H.da.node,c.A=N.H.da.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.B[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Ba(a){return a.B?a.B.subarray?a.B.subarray(0,a.D):new Uint8Array(a.B):new Uint8Array(0)},C:{K(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;O(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.D:40960===(a.mode&61440)?b.size=a.link.length:
b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},I(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.D!=b&&(0==b?(a.B=null,a.D=0):(c=a.B,a.B=new Uint8Array(b),c&&a.B.set(c.subarray(0,Math.min(b,a.D))),a.D=b)))},lookup(){throw N.ea;},S(a,b,c,d){return N.createNode(a,b,c,d)},rename(a,b,c){try{var d=P(b,c)}catch(f){}if(d){if(O(a.mode))for(var e in d.B)throw new M(55);
ab(d)}delete a.parent.B[a.name];b.B[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.B[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=P(a,b),d;for(d in c.B)throw new M(55);delete a.B[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.B)]},symlink(a,b,c){a=N.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new M(28);return a.link}},A:{read(a,b,c,d,e){var f=a.node.B;if(e>=a.node.D)return 0;a=Math.min(a.node.D-
e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===C.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.B||a.B.subarray)){if(f)return a.B=b.subarray(c,c+d),a.D=d;if(0===a.D&&0===e)return a.B=b.slice(c,c+d),a.D=d;if(e+d<=a.D)return a.B.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.B?a.B.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.B,a.B=new Uint8Array(f),
0<a.D&&a.B.set(g.subarray(0,a.D),0));if(a.B.subarray&&b.subarray)a.B.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.B[e+f]=b[c+f];a.D=Math.max(a.D,e+d);return d},G(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.D);if(0>b)throw new M(28);return b},O(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new M(43);a=a.node.B;if(e&2||!a||a.buffer!==C.buffer){d=!0;e=Ya(b);if(!e)throw new M(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);C.set(a,e>>>0)}}else d=!1,e=a.byteOffset;return{ia:e,ba:d}},T(a,b,c,d){N.A.write(a,b,0,d,c,!1);return 0}}},bb=async a=>{a=await pa(a);return new Uint8Array(a)},cb=h.preloadPlugins||[],db=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.Ca();var e=!1;cb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},fb=(a,b,c,d,e,f,g,p,r,m)=>{function t(x){function v(w){m?.();p||eb(a,b,w,d,e,r);f?.();xa(q)}db(x,l,v,()=>{g?.();xa(q)})||v(x)}var l=b?Ma(L(a+"/"+b)):a,q=`cp ${l}`;wa(q);"string"==
typeof c?bb(c).then(t,g):t(c)},gb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},hb=null,ib={},Q=[],jb=1,R=null,kb=!1,lb=!0,mb={},M=class{name="ErrnoError";constructor(a){this.F=a}},nb=class{J={};node=null;get flags(){return this.J.flags}set flags(a){this.J.flags=a}get position(){return this.J.position}set position(a){this.J.position=a}},ob=class{C={};A={};P=null;constructor(a,b,c,d){a||=this;this.parent=a;this.L=a.L;this.id=jb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=
Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get qa(){return O(this.mode)}get pa(){return 8192===(this.mode&61440)}};
function S(a,b={}){if(!a)throw new M(44);b.W??(b.W=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(p=>!!p);for(var d=hb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])e=Ja(e),d=d.parent;else{e=L(e+"/"+a[f]);try{d=P(d,a[f])}catch(p){if(44===p?.F&&g&&b.sa)return{path:e};throw p;}!d.P||g&&!b.W||(d=d.P.root);if(40960===(d.mode&61440)&&(!g||b.R)){if(!d.C.readlink)throw new M(52);d=d.C.readlink(d);"/"===d.charAt(0)||(d=Ja(e)+
"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new M(32);}function pb(a){for(var b;;){if(a===a.parent)return a=a.L.ha,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function qb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}function ab(a){var b=qb(a.parent.id,a.name);if(R[b]===a)R[b]=a.N;else for(b=R[b];b;){if(b.N===a){b.N=a.N;break}b=b.N}}
function P(a,b){var c=O(a.mode)?(c=rb(a,"x"))?c:a.C.lookup?0:2:54;if(c)throw new M(c);for(c=R[qb(a.id,b)];c;c=c.N){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.C.lookup(a,b)}function $a(a,b,c,d){a=new ob(a,b,c,d);b=qb(a.parent.id,a.name);a.N=R[b];return R[b]=a}function O(a){return 16384===(a&61440)}function sb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function rb(a,b){if(lb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function tb(a,b){if(!O(a.mode))return 54;try{return P(a,b),20}catch(c){}return rb(a,"wx")}function ub(a){if(!a)throw new M(63);return a}function T(a){a=Q[a];if(!a)throw new M(8);return a}function vb(a,b=-1){a=Object.assign(new nb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!Q[b])break a;throw new M(33);}a.fd=b;return Q[b]=a}
function wb(a,b=-1){a=vb(a,b);a.A?.Aa?.(a);return a}function xb(a,b){var c=null?.A.I,d=c?null:a;c??=a.C.I;ub(c);c(d,b)}var Za={open(a){a.A=ib[a.node.rdev].A;a.A.open?.(a)},G(){throw new M(70);}};function Ta(a,b){ib[a]={A:b}}function yb(a,b){var c="/"===b;if(c&&hb)throw new M(10);if(!c&&b){var d=S(b,{W:!1});b=d.path;d=d.node;if(d.P)throw new M(10);if(!O(d.mode))throw new M(54);}b={type:a,Da:{},ha:b,ra:[]};a=a.L(b);a.L=b;b.root=a;c?hb=a:d&&(d.P=b,d.L&&d.L.ra.push(b))}
function zb(a,b,c){var d=S(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new M(28);if("."===a||".."===a)throw new M(20);var e=tb(d,a);if(e)throw new M(e);if(!d.C.S)throw new M(63);return d.C.S(d,a,b,c)}function Ab(a,b=438){return zb(a,b&4095|32768,0)}function U(a){return zb(a,16895,0)}function Bb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return zb(a,b|8192,c)}
function Cb(a,b){if(!Ma(a))throw new M(44);var c=S(b,{parent:!0}).node;if(!c)throw new M(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=tb(c,b);if(d)throw new M(d);if(!c.C.symlink)throw new M(63);c.C.symlink(c,b,a)}
function Db(a){var b=S(a,{parent:!0}).node;if(!b)throw new M(44);a=a&&a.match(/([^\/]+|\/)\/*$/)[1];var c=P(b,a);a:{try{var d=P(b,a)}catch(f){d=f.F;break a}var e=rb(b,"wx");d=e?e:O(d.mode)?31:0}if(d)throw new M(d);if(!b.C.unlink)throw new M(63);if(c.P)throw new M(10);b.C.unlink(b,a);ab(c)}function Eb(a,b){a="string"==typeof a?S(a,{R:!0}).node:a;xb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),za:void 0})}
function k(a,b,c=438){if(""===a)throw new M(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=S(a,{R:!(b&131072),sa:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new M(20);}else{if(e)throw new M(31);d=zb(a,c|511,0);f=!0}if(!d)throw new M(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!O(d.mode))throw new M(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:O(d.mode)&&("r"!==sb(b)||b&576)?31:rb(d,sb(b)):44))throw new M(e);if(b&512&&!f){e=d;e="string"==typeof e?S(e,{R:!0}).node:e;if(O(e.mode))throw new M(31);if(32768!==(e.mode&61440))throw new M(28);var g=rb(e,"w");if(g)throw new M(g);xb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=vb({node:d,path:pb(d),flags:b,seekable:!0,position:0,A:d.A,ta:[],error:!1});e.A.open&&e.A.open(e);f&&Eb(d,c&511);!h.logReadFiles||b&1||a in mb||(mb[a]=1);return e}
function ka(a){if(null===a.fd)throw new M(8);a.X&&(a.X=null);try{a.A.close&&a.A.close(a)}catch(b){throw b;}finally{Q[a.fd]=null}a.fd=null}function Fb(a,b,c){if(null===a.fd)throw new M(8);if(!a.seekable||!a.A.G)throw new M(70);if(0!=c&&1!=c&&2!=c)throw new M(28);a.position=a.A.G(a,b,c);a.ta=[]}
function ja(a,b,c,d,e,f){if(0>d||0>e)throw new M(28);if(null===a.fd)throw new M(8);if(0===(a.flags&2097155))throw new M(8);if(O(a.node.mode))throw new M(31);if(!a.A.write)throw new M(28);a.seekable&&a.flags&1024&&Fb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new M(70);b=a.A.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Gb(a,b){a="string"==typeof a?a:pb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=L(a+"/"+c);try{U(d)}catch(e){if(20!=e.F)throw e;}a=d}}return d}function Hb(a,b,c,d){a=L(("string"==typeof a?a:pb(a))+"/"+b);return Ab(a,gb(c,d))}
function eb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:pb(a),g=b?L(a+"/"+b):a);a=gb(d,e);g=Ab(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Eb(g,a|146);b=k(g,577);ja(b,c,0,c.length,0,f);ka(b);Eb(g,a)}}
function V(a,b,c,d){a=L(("string"==typeof a?a:pb(a))+"/"+b);b=gb(!!c,!!d);V.ga??(V.ga=64);var e=V.ga++<<8|0;Ta(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,p,r){for(var m=0,t=0;t<r;t++){try{var l=c()}catch(q){throw new M(29);}if(void 0===l&&0===m)throw new M(6);if(null===l||void 0===l)break;m++;g[p+t]=l}m&&(f.node.atime=Date.now());return m},write(f,g,p,r){for(var m=0;m<r;m++)try{d(g[p+m])}catch(t){throw new M(29);}r&&(f.node.mtime=f.node.ctime=Date.now());return m}});return Bb(a,
b,e)}function Ib(a){if(!(a.pa||a.qa||a.link||a.B)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.B=y(a.url),a.D=a.B.length}catch(b){throw new M(29);}}}
function Jb(a,b,c,d,e){function f(l,q,x,v,w){l=l.node.B;if(w>=l.length)return 0;v=Math.min(l.length-w,v);if(l.slice)for(var u=0;u<v;u++)q[x+u]=l[w+u];else for(u=0;u<v;u++)q[x+u]=l.get(w+u);return v}class g{V=!1;J=[];U=void 0;$=0;Z=0;get(l){if(!(l>this.length-1||0>l)){var q=l%this.chunkSize;return this.U(l/this.chunkSize|0)[q]}}ja(l){this.U=l}aa(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+c+". Status: "+
l.status);var q=Number(l.getResponseHeader("Content-length")),x,v=(x=l.getResponseHeader("Accept-Ranges"))&&"bytes"===x;l=(x=l.getResponseHeader("Content-Encoding"))&&"gzip"===x;var w=1048576;v||(w=q);var u=this;u.ja(J=>{var K=J*w,X=(J+1)*w-1;X=Math.min(X,q-1);if("undefined"==typeof u.J[J]){var Sb=u.J;if(K>X)throw Error("invalid range ("+K+", "+X+") or no bytes requested!");if(X>q-1)throw Error("only "+q+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",c,!1);q!==w&&B.setRequestHeader("Range",
"bytes="+K+"-"+X);B.responseType="arraybuffer";B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>B.status||304===B.status))throw Error("Couldn't load "+c+". Status: "+B.status);K=void 0!==B.response?new Uint8Array(B.response||[]):Qa(B.responseText||"");Sb[J]=K}if("undefined"==typeof u.J[J])throw Error("doXHR failed!");return u.J[J]});if(l||!q)w=q=1,w=q=this.U(0).length,ra("LazyFiles on gzip forces download of the whole file when length is accessed");
this.$=q;this.Z=w;this.V=!0}get length(){this.V||this.aa();return this.$}get chunkSize(){this.V||this.aa();return this.Z}}if("undefined"!=typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var p=new g;var r=void 0}else r=c,p=void 0;var m=Hb(a,b,d,e);p?m.B=p:r&&(m.B=null,m.url=r);Object.defineProperties(m,{D:{get:function(){return this.B.length}}});var t={};Object.keys(m.A).forEach(l=>{var q=m.A[l];
t[l]=(...x)=>{Ib(m);return q(...x)}});t.read=(l,q,x,v,w)=>{Ib(m);return f(l,q,x,v,w)};t.O=(l,q,x)=>{Ib(m);var v=Ya(q);if(!v)throw new M(48);f(l,C,v,q,x);return{ia:v,ba:!0}};m.A=t;return m}
var W={},Kb=a=>(a>>>=0)?Oa(D,a):"",Lb=void 0,Y=()=>{var a=E[+Lb>>>2>>>0];Lb+=4;return a},Mb={},Ob=()=>{if(!Nb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:na||"./this.program"},b;for(b in Mb)void 0===Mb[b]?delete a[b]:a[b]=Mb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Nb=c}return Nb},Nb,Rb=a=>{if(!Ha){Pb();kb=!1;Qb(0);for(var b of Q)b&&ka(b)}Ha||(h.onExit?.(a),
ta=!0);oa(a,new Ca(a))};R=Array(4096);yb(N,"/");U("/tmp");U("/home");U("/home/web_user");(function(){U("/dev");Ta(259,{read:()=>0,write:(d,e,f,g)=>g,G:()=>0});Bb("/dev/null",259);Sa(1280,Va);Sa(1536,Wa);Bb("/dev/tty",1280);Bb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(La(a),b=a.byteLength);return a[--b]};V("/dev","random",c);V("/dev","urandom",c);U("/dev/shm");U("/dev/shm/tmp")})();
(function(){U("/proc");var a=U("/proc/self");U("/proc/self/fd");yb({L(){var b=$a(a,"fd",16895,73);b.A={G:N.A.G};b.C={lookup(c,d){c=+d;var e=T(c);c={parent:null,L:{ha:"fake"},C:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(Q.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.FS_createPath=Gb;h.FS_createDataFile=eb;h.FS_createPreloadedFile=fb;h.FS_unlink=Db;h.FS_createLazyFile=Jb;h.FS_createDevice=V;N.ea=new M(44);N.ea.stack="<generic error, no stack>";
var Tb={k:function(a){try{var b=T(a);return wb(b).fd}catch(c){if("undefined"==typeof W||"ErrnoError"!==c.name)throw c;return-c.F}},f:function(a,b,c){Lb=c>>>0;try{var d=T(a);switch(b){case 0:var e=Y();if(0>e)break;for(;Q[e];)e++;return wb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Y(),d.flags|=e,0;case 12:return e=Y(),ua[e+0>>>1>>>0]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof W||"ErrnoError"!==f.name)throw f;return-f.F}},j:function(a,b,c){Lb=c>>>
0;try{var d=T(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.M.ma){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Y();E[e>>>2>>>0]=25856;E[e+4>>>2>>>0]=5;E[e+8>>>2>>>0]=191;E[e+12>>>2>>>0]=35387;for(var f=0;32>f;f++)C[e+f+17>>>0]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.M.na)for(e=Y(),a=[],f=0;32>f;f++)a.push(C[e+f+17>>>0]);return 0;case 21519:if(!d.tty)return-59;
e=Y();return E[e>>>2>>>0]=0;case 21520:return d.tty?-28:-59;case 21531:e=Y();if(!d.A.la)throw new M(59);return d.A.la(d,b,e);case 21523:if(!d.tty)return-59;d.tty.M.oa&&(f=[24,80],e=Y(),ua[e>>>1>>>0]=f[0],ua[e+2>>>1>>>0]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof W||"ErrnoError"!==g.name)throw g;return-g.F}},g:function(a,b,c,d){b>>>=0;Lb=d>>>=0;try{b=Kb(b);var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":T(a).path;
if(0==e.length)throw new M(44);b=f+"/"+e}var g=d?Y():0;return k(b,c,g).fd}catch(p){if("undefined"==typeof W||"ErrnoError"!==p.name)throw p;return-p.F}},m:function(a,b){a>>>=0;b>>>=0;try{a=Kb(a);var c=S(a,{R:!0}).node;var d=ub(c.C.K)(c);E[b>>>2>>>0]=d.dev;E[b+4>>>2>>>0]=d.mode;F[b+8>>>2>>>0]=d.nlink;E[b+12>>>2>>>0]=d.uid;E[b+16>>>2>>>0]=d.gid;E[b+20>>>2>>>0]=d.rdev;G[b+24>>>3]=BigInt(d.size);E[b+32>>>2>>>0]=4096;E[b+36>>>2>>>0]=d.blocks;var e=d.atime.getTime(),f=d.mtime.getTime(),g=d.ctime.getTime();
G[b+40>>>3]=BigInt(Math.floor(e/1E3));F[b+48>>>2>>>0]=e%1E3*1E6;G[b+56>>>3]=BigInt(Math.floor(f/1E3));F[b+64>>>2>>>0]=f%1E3*1E6;G[b+72>>>3]=BigInt(Math.floor(g/1E3));F[b+80>>>2>>>0]=g%1E3*1E6;G[b+88>>>3]=BigInt(d.ino);return 0}catch(p){if("undefined"==typeof W||"ErrnoError"!==p.name)throw p;return-p.F}},n:function(a,b,c,d,e,f,g){a>>>=0;e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);f>>>=0;g>>>=0;try{if(isNaN(e))return 61;var p=T(d);if(0!==(b&2)&&0===(c&2)&&2!==(p.flags&2097155))throw new M(2);
if(1===(p.flags&2097155))throw new M(2);if(!p.A.O)throw new M(43);if(!a)throw new M(28);var r=p.A.O(p,a,e,b,c);var m=r.ia;E[f>>>2>>>0]=r.ba;F[g>>>2>>>0]=m;return 0}catch(t){if("undefined"==typeof W||"ErrnoError"!==t.name)throw t;return-t.F}},o:function(a,b,c,d,e,f){a>>>=0;b>>>=0;f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=T(e);if(c&2){if(32768!==(g.node.mode&61440))throw new M(43);if(!(d&2)){var p=D.slice(a,a+b);g.A.T&&g.A.T(g,p,f,b,d)}}}catch(r){if("undefined"==typeof W||"ErrnoError"!==
r.name)throw r;return-r.F}},h:()=>Date.now(),l:function(a){a>>>=0;var b=D.length;if(4294901760<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(4294901760,65536*Math.ceil(Math.max(a,d)/65536))-A.buffer.byteLength+65535)/65536|0;try{A.grow(d);va();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},q:function(a,b){a>>>=0;b>>>=0;var c=0;Ob().forEach((d,e)=>{var f=b+c;e=F[a+4*e>>>2>>>0]=f;for(f=0;f<d.length;++f)C[e++>>>0]=d.charCodeAt(f);C[e>>>0]=0;c+=
d.length+1});return 0},i:function(a,b){a>>>=0;b>>>=0;var c=Ob();F[a>>>2>>>0]=c.length;var d=0;c.forEach(e=>d+=e.length+1);F[b>>>2>>>0]=d;return 0},d:Rb,c:function(a){try{var b=T(a);ka(b);return 0}catch(c){if("undefined"==typeof W||"ErrnoError"!==c.name)throw c;return c.F}},e:function(a,b,c,d){b>>>=0;c>>>=0;d>>>=0;try{a:{var e=T(a);a=b;for(var f,g=b=0;g<c;g++){var p=F[a>>>2>>>0],r=F[a+4>>>2>>>0];a+=8;var m=e,t=p,l=r,q=f,x=C;if(0>l||0>q)throw new M(28);if(null===m.fd)throw new M(8);if(1===(m.flags&
2097155))throw new M(8);if(O(m.node.mode))throw new M(31);if(!m.A.read)throw new M(28);var v="undefined"!=typeof q;if(!v)q=m.position;else if(!m.seekable)throw new M(70);var w=m.A.read(m,x,t,l,q);v||(m.position+=w);var u=w;if(0>u){var J=-1;break a}b+=u;if(u<r)break;"undefined"!=typeof f&&(f+=u)}J=b}F[d>>>2>>>0]=J;return 0}catch(K){if("undefined"==typeof W||"ErrnoError"!==K.name)throw K;return K.F}},p:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);d>>>=0;try{if(isNaN(b))return 61;
var e=T(a);Fb(e,b,c);G[d>>>3]=BigInt(e.position);e.X&&0===b&&0===c&&(e.X=null);return 0}catch(f){if("undefined"==typeof W||"ErrnoError"!==f.name)throw f;return f.F}},b:function(a,b,c,d){b>>>=0;c>>>=0;d>>>=0;try{a:{var e=T(a);a=b;for(var f,g=b=0;g<c;g++){var p=F[a>>>2>>>0],r=F[a+4>>>2>>>0];a+=8;var m=ja(e,C,p,r,f);if(0>m){var t=-1;break a}b+=m;if(m<r)break;"undefined"!=typeof f&&(f+=m)}t=b}F[d>>>2>>>0]=t;return 0}catch(l){if("undefined"==typeof W||"ErrnoError"!==l.name)throw l;return l.F}},a:A},Z=
await (async function(){function a(d){Z=d.exports;Z=Ub();xa("wasm-instantiate");return Z}wa("wasm-instantiate");var b={a:Tb};if(h.instantiateWasm)return new Promise(d=>{h.instantiateWasm(b,(e,f)=>{a(e,f);d(e.exports)})});ya??=h.locateFile?h.locateFile("xmllint.wasm",n):n+"xmllint.wasm";try{var c=await Ba(b);return a(c.instance)}catch(d){return ba(d),Promise.reject(d)}}()),Vb=h._main=Z.s,Qb=Z.u,Pb=Z.v,Xa=Z.w,Wb=Z.x;
function Ub(){var a=Z;a=Object.assign({},a);a.w=(b=>(c,d)=>b(c,d)>>>0)(a.w);a.x=(b=>c=>b(c)>>>0)(a.x);a.emscripten_stack_get_current=(b=>()=>b()>>>0)(a.emscripten_stack_get_current);return a}h.addRunDependency=wa;h.removeRunDependency=xa;h.FS_createPreloadedFile=fb;h.FS_unlink=a=>Db(a);h.FS_createPath=Gb;h.FS_createDevice=V;h.FS_createDataFile=(a,b,c,d,e,f)=>{eb(a,b,c,d,e,f)};h.FS_createLazyFile=Jb;
function Xb(a=[]){a.unshift(na);var b=a.length,c=Wb(4*(b+1)),d=c;a.forEach(f=>{var g=F,p=d>>>2>>>0,r=ha(f)+1,m=Wb(r);ia(f,D,m,r);g[p]=m;d+=4});F[d>>>2>>>0]=0;try{var e=Vb(b,c);Rb(e,!0)}catch(f){f instanceof Ca||"unwind"==f||oa(1,f)}}
function Yb(a=ma){function b(){h.calledRun=!0;if(!ta){if(!h.noFSInit&&!kb){var c,d;kb=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?V("/dev","stdin",c):Cb("/dev/tty","/dev/stdin");d?V("/dev","stdout",null,d):Cb("/dev/tty","/dev/stdout");e?V("/dev","stderr",null,e):Cb("/dev/tty1","/dev/stderr");k("/dev/stdin",0);k("/dev/stdout",1);k("/dev/stderr",1)}Z.r();lb=!1;aa(h);h.onRuntimeInitialized?.();h.noInitialRun||Xb(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();Ea.unshift(e)}Da(Ea)}}if(0<H)I=Yb;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ga();Da(Fa);0<H?I=Yb:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();Yb();moduleRtn=ca;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object') {
  module.exports = Module;
  // This default export looks redundant, but it allows TS to import this
  // commonjs style module.
  module.exports.default = Module;
} else if (typeof define === 'function' && define['amd'])
  define([], () => Module);
;(function initWorker() {
	const {parentPort} = require('worker_threads');

	let stdout = '';
	let stderr = '';

	function onExit(exitCode) {
		const message = {
			exitCode,
			stdout,
			stderr,
		};
		parentPort.postMessage(message);
	};
	function onWorkerMessage(event) {
		var data = event;
		const wasmMemory = new WebAssembly.Memory({
			initial: data.initialMemory,
			maximum: data.maxMemory
		});

		Module({
			inputFiles: data.inputFiles,
			arguments: data.args,
			// TODO: We could eagerly start sending stdout to the parent thread while
			// waiting for more. Or we could probably use some other, more efficient
			// Emscripten API for output communication in the first place.
			// But this seems to work fine for now, better than pushing the stdout
			// values to an array.
			print(text) {
				stdout += text + '\n';
			},
			printErr(text) {
				stderr += text + '\n';
			},
			onExit,
			onAbort(reason) {
				const message = {
					exitCode: -1,
					stdout: '',
					stderr: 'WASM Abort: ' + reason,
				};
				parentPort.postMessage(message);
			},
			wasmMemory,
		});
	}


	parentPort.on('message', onWorkerMessage);
})();
