# CẤU HÌNH H2 CHO MÔI TRƯỜNG TEST
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MSSQLServer
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Cấu hình bảo mật cho Test
jwt.secret=rexi_test_secret_key_rexi_test_secret_key_rexi_test_secret_key
jwt.expiration=3600000

# Tắt Email khi Test
spring.mail.host=localhost
